//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clock.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Clock.Locales.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock.
        /// </summary>
        public static string Clock {
            get {
                return ResourceManager.GetString("Clock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a clock for a city to check the time at that location.
        /// </summary>
        public static string Clock_Analog_Subtitle {
            get {
                return ResourceManager.GetString("Clock_Analog_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog I.
        /// </summary>
        public static string Clock_AnalogI_Title {
            get {
                return ResourceManager.GetString("Clock_AnalogI_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog II.
        /// </summary>
        public static string Clock_AnalogII_Title {
            get {
                return ResourceManager.GetString("Clock_AnalogII_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analog III.
        /// </summary>
        public static string Clock_AnalogIII_Title {
            get {
                return ResourceManager.GetString("Clock_AnalogIII_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital.
        /// </summary>
        public static string Clock_Digital_Title {
            get {
                return ResourceManager.GetString("Clock_Digital_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use local time zone.
        /// </summary>
        public static string Clock_LocalTimeZone {
            get {
                return ResourceManager.GetString("Clock_LocalTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show date.
        /// </summary>
        public static string Clock_ShowDate {
            get {
                return ResourceManager.GetString("Clock_ShowDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show seconds.
        /// </summary>
        public static string Clock_ShowSeconds {
            get {
                return ResourceManager.GetString("Clock_ShowSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time zone.
        /// </summary>
        public static string Clock_TimeZone {
            get {
                return ResourceManager.GetString("Clock_TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City name.
        /// </summary>
        public static string Clock_CityName {
            get {
                return ResourceManager.GetString("Clock_CityName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Clock_Today {
            get {
                return ResourceManager.GetString("Clock_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string Clock_Tomorrow {
            get {
                return ResourceManager.GetString("Clock_Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-hour time.
        /// </summary>
        public static string Clock_Use24Hours {
            get {
                return ResourceManager.GetString("Clock_Use24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the time in multiple cities from around the world.
        /// </summary>
        public static string Clock_World_Subtitle {
            get {
                return ResourceManager.GetString("Clock_World_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Clock.
        /// </summary>
        public static string Clock_World_Title {
            get {
                return ResourceManager.GetString("Clock_World_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Clock_Yesterday {
            get {
                return ResourceManager.GetString("Clock_Yesterday", resourceCulture);
            }
        }
        
        public static string Clock_FramelessDigital_Title {
            get {
                return ResourceManager.GetString("Clock_FramelessDigital_Title", resourceCulture);
            }
        }

        public static string Clock_FramelessDigital_Subtitle {
            get {
                return ResourceManager.GetString("Clock_FramelessDigital_Subtitle", resourceCulture);
            }
        }

        public static string Clock_FontFamily {
            get {
                return ResourceManager.GetString("Clock_FontFamily", resourceCulture);
            }
        }

        public static string Clock_FontFamily_Default {
            get {
                return ResourceManager.GetString("Clock_FontFamily_Default", resourceCulture);
            }
        }

        public static string Clock_StretchFill {
            get {
                return ResourceManager.GetString("Clock_StretchFill", resourceCulture);
            }
        }

        public static string Clock_StretchFill_Subtitle {
            get {
                return ResourceManager.GetString("Clock_StretchFill_Subtitle", resourceCulture);
            }
        }

        public static string Clock_EnableOverlay {
            get {
                return ResourceManager.GetString("Clock_EnableOverlay", resourceCulture);
            }
        }

        public static string Clock_EnableOverlay_Subtitle {
            get {
                return ResourceManager.GetString("Clock_EnableOverlay_Subtitle", resourceCulture);
            }
        }

        public static string Clock_FollowAccentColor {
            get {
                return ResourceManager.GetString("Clock_FollowAccentColor", resourceCulture);
            }
        }

        public static string Clock_OverlayColor {
            get {
                return ResourceManager.GetString("Clock_OverlayColor", resourceCulture);
            }
        }

        public static string Clock_OverlayOpacity {
            get {
                return ResourceManager.GetString("Clock_OverlayOpacity", resourceCulture);
            }
        }

        public static string Clock_FontWeight {
            get {
                return ResourceManager.GetString("Clock_FontWeight", resourceCulture);
            }
        }

        public static string Clock_FontWeight_100 {
            get {
                return ResourceManager.GetString("Clock_FontWeight_100", resourceCulture);
            }
        }

        public static string Clock_FontWeight_200 {
            get {
                return ResourceManager.GetString("Clock_FontWeight_200", resourceCulture);
            }
        }

        public static string Clock_FontWeight_300 {
            get {
                return ResourceManager.GetString("Clock_FontWeight_300", resourceCulture);
            }
        }

        public static string Clock_FontWeight_400 {
            get {
                return ResourceManager.GetString("Clock_FontWeight_400", resourceCulture);
            }
        }

        public static string Clock_FontWeight_500 {
            get {
                return ResourceManager.GetString("Clock_FontWeight_500", resourceCulture);
            }
        }

        public static string Clock_FontWeight_600 {
            get {
                return ResourceManager.GetString("Clock_FontWeight_600", resourceCulture);
            }
        }

        public static string Clock_FontWeight_700 {
            get {
                return ResourceManager.GetString("Clock_FontWeight_700", resourceCulture);
            }
        }

        public static string Clock_FontWeight_800 {
            get {
                return ResourceManager.GetString("Clock_FontWeight_800", resourceCulture);
            }
        }

        public static string Clock_FontWeight_900 {
            get {
                return ResourceManager.GetString("Clock_FontWeight_900", resourceCulture);
            }
        }

        public static string Clock_ThemeMode {
            get {
                return ResourceManager.GetString("Clock_ThemeMode", resourceCulture);
            }
        }

        public static string Clock_ThemeMode_FollowGlobal {
            get {
                return ResourceManager.GetString("Clock_ThemeMode_FollowGlobal", resourceCulture);
            }
        }

        public static string Clock_ThemeMode_Acrylic {
            get {
                return ResourceManager.GetString("Clock_ThemeMode_Acrylic", resourceCulture);
            }
        }

        public static string Clock_ThemeMode_LiquidGlass {
            get {
                return ResourceManager.GetString("Clock_ThemeMode_LiquidGlass", resourceCulture);
            }
        }

        public static string Clock_ThemeMode_Solid {
            get {
                return ResourceManager.GetString("Clock_ThemeMode_Solid", resourceCulture);
            }
        }

        public static string Clock_DyeIntensity {
            get {
                return ResourceManager.GetString("Clock_DyeIntensity", resourceCulture);
            }
        }

        public static string Clock_DyeIntensity_Subtitle {
            get {
                return ResourceManager.GetString("Clock_DyeIntensity_Subtitle", resourceCulture);
            }
        }

        public static string Clock_RefractionWidth {
            get {
                return ResourceManager.GetString("Clock_RefractionWidth", resourceCulture);
            }
        }

        public static string Clock_RefractionWidth_Subtitle {
            get {
                return ResourceManager.GetString("Clock_RefractionWidth_Subtitle", resourceCulture);
            }
        }
    }
}
