//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools.Locales {
    using System;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tools.Locales.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Tools => ResourceManager.GetString("Tools", resourceCulture) ?? "Tools";
        public static string Tools_Clipboard_Title => ResourceManager.GetString("Tools_Clipboard_Title", resourceCulture) ?? "Clipboard";
        public static string Tools_Clipboard_Subtitle => ResourceManager.GetString("Tools_Clipboard_Subtitle", resourceCulture) ?? "Track clipboard history of text, images, and files";
        public static string Tools_Clipboard_Empty => ResourceManager.GetString("Tools_Clipboard_Empty", resourceCulture) ?? "Clipboard history is empty";
        public static string Tools_Clipboard_Clear => ResourceManager.GetString("Tools_Clipboard_Clear", resourceCulture) ?? "Clear History";
        public static string Tools_Clipboard_Copied => ResourceManager.GetString("Tools_Clipboard_Copied", resourceCulture) ?? "Copied to clipboard";
        public static string Tools_Clipboard_All => ResourceManager.GetString("Tools_Clipboard_All", resourceCulture) ?? "All";
        public static string Tools_Clipboard_Text => ResourceManager.GetString("Tools_Clipboard_Text", resourceCulture) ?? "Text";
        public static string Tools_Clipboard_Image => ResourceManager.GetString("Tools_Clipboard_Image", resourceCulture) ?? "Image";
        public static string Tools_Clipboard_Files => ResourceManager.GetString("Tools_Clipboard_Files", resourceCulture) ?? "Files";
        public static string Tools_Clipboard_MaxHistory => ResourceManager.GetString("Tools_Clipboard_MaxHistory", resourceCulture) ?? "Max items";
        public static string Tools_Clipboard_MaxHistory_Desc => ResourceManager.GetString("Tools_Clipboard_MaxHistory_Desc", resourceCulture) ?? "Number of recent items to keep in history (5 - 100)";
        public static string Tools_Clipboard_ClearCache => ResourceManager.GetString("Tools_Clipboard_ClearCache", resourceCulture) ?? "Clear image cache";
        public static string Tools_Clipboard_AutoCopy => ResourceManager.GetString("Tools_Clipboard_AutoCopy", resourceCulture) ?? "Click card to copy";
        public static string Tools_Clipboard_AutoCopy_Desc => ResourceManager.GetString("Tools_Clipboard_AutoCopy_Desc", resourceCulture) ?? "Instantly copy to Windows clipboard when clicking a history card";

        public static string Tools_Translator_Title => ResourceManager.GetString("Tools_Translator_Title", resourceCulture) ?? "Translator";
        public static string Tools_Translator_Subtitle => ResourceManager.GetString("Tools_Translator_Subtitle", resourceCulture) ?? "Fast bilingual translation with multiple engine sources";
        public static string Tools_Translator_InputHint => ResourceManager.GetString("Tools_Translator_InputHint", resourceCulture) ?? "Enter text to translate...";
        public static string Tools_Translator_OutputHint => ResourceManager.GetString("Tools_Translator_OutputHint", resourceCulture) ?? "Translation result will appear here";
        public static string Tools_Translator_Translate => ResourceManager.GetString("Tools_Translator_Translate", resourceCulture) ?? "Translate";
        public static string Tools_Translator_Translating => ResourceManager.GetString("Tools_Translator_Translating", resourceCulture) ?? "Translating...";
        public static string Tools_Translator_Copy => ResourceManager.GetString("Tools_Translator_Copy", resourceCulture) ?? "Copy";
        public static string Tools_Translator_Clear => ResourceManager.GetString("Tools_Translator_Clear", resourceCulture) ?? "Clear";
        public static string Tools_Translator_Swap => ResourceManager.GetString("Tools_Translator_Swap", resourceCulture) ?? "Swap Languages";
        public static string Tools_Translator_Engine => ResourceManager.GetString("Tools_Translator_Engine", resourceCulture) ?? "Translation Engine";
        public static string Tools_Translator_Engine_Desc => ResourceManager.GetString("Tools_Translator_Engine_Desc", resourceCulture) ?? "Choose default translation service";
        public static string Tools_Translator_Auto => ResourceManager.GetString("Tools_Translator_Auto", resourceCulture) ?? "Auto Detect";
        public static string Tools_Translator_Zh => ResourceManager.GetString("Tools_Translator_Zh", resourceCulture) ?? "Chinese";
        public static string Tools_Translator_En => ResourceManager.GetString("Tools_Translator_En", resourceCulture) ?? "English";
        public static string Tools_Translator_Ja => ResourceManager.GetString("Tools_Translator_Ja", resourceCulture) ?? "Japanese";
        public static string Tools_Translator_Ko => ResourceManager.GetString("Tools_Translator_Ko", resourceCulture) ?? "Korean";
        public static string Tools_Translator_Fr => ResourceManager.GetString("Tools_Translator_Fr", resourceCulture) ?? "French";
        public static string Tools_Translator_De => ResourceManager.GetString("Tools_Translator_De", resourceCulture) ?? "German";
        public static string Tools_Translator_Es => ResourceManager.GetString("Tools_Translator_Es", resourceCulture) ?? "Spanish";
        public static string Tools_Translator_Ru => ResourceManager.GetString("Tools_Translator_Ru", resourceCulture) ?? "Russian";
        public static string Tools_Translator_Engine_Youdao => ResourceManager.GetString("Tools_Translator_Engine_Youdao", resourceCulture) ?? "Youdao (Direct, Free)";
        public static string Tools_Translator_Engine_MyMemory => ResourceManager.GetString("Tools_Translator_Engine_MyMemory", resourceCulture) ?? "MyMemory (Direct, Free)";
        public static string Tools_Translator_Engine_Baidu => ResourceManager.GetString("Tools_Translator_Engine_Baidu", resourceCulture) ?? "Baidu (Personal AppID)";
        public static string Tools_Translator_Engine_DeepLX => ResourceManager.GetString("Tools_Translator_Engine_DeepLX", resourceCulture) ?? "DeepLX (Custom Endpoint)";
        public static string Tools_Translator_BaiduAppId => ResourceManager.GetString("Tools_Translator_BaiduAppId", resourceCulture) ?? "Baidu AppID";
        public static string Tools_Translator_BaiduSecret => ResourceManager.GetString("Tools_Translator_BaiduSecret", resourceCulture) ?? "Baidu Secret Key";
        public static string Tools_Translator_CustomUrl => ResourceManager.GetString("Tools_Translator_CustomUrl", resourceCulture) ?? "Custom Endpoint URL";
        public static string Tools_Translator_AutoTranslate => ResourceManager.GetString("Tools_Translator_AutoTranslate", resourceCulture) ?? "Translate as you type";
        public static string Tools_Translator_AutoTranslate_Desc => ResourceManager.GetString("Tools_Translator_AutoTranslate_Desc", resourceCulture) ?? "Automatically trigger translation after typing pauses";
    }
}
