//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uWidgets.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uWidgets.Locales.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Settings_About {
            get {
                return ResourceManager.GetString("Settings_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Settings_About_Actions {
            get {
                return ResourceManager.GetString("Settings_About_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug.
        /// </summary>
        public static string Settings_About_ReportBug {
            get {
                return ResourceManager.GetString("Settings_About_ReportBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub repository.
        /// </summary>
        public static string Settings_About_Repository {
            get {
                return ResourceManager.GetString("Settings_About_Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit.
        /// </summary>
        public static string Settings_About_Repository_Action {
            get {
                return ResourceManager.GetString("Settings_About_Repository_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My repository.
        /// </summary>
        public static string Settings_About_MyRepository {
            get {
                return ResourceManager.GetString("Settings_About_MyRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original author's repository.
        /// </summary>
        public static string Settings_About_OriginalRepository {
            get {
                return ResourceManager.GetString("Settings_About_OriginalRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug to the original author.
        /// </summary>
        public static string Settings_About_OriginalReportBug {
            get {
                return ResourceManager.GetString("Settings_About_OriginalReportBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Settings_About_Version {
            get {
                return ResourceManager.GetString("Settings_About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run the application as Administrator to change this setting.
        /// </summary>
        public static string Settings_AdminRequired {
            get {
                return ResourceManager.GetString("Settings_AdminRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Settings_Advanced {
            get {
                return ResourceManager.GetString("Settings_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Settings_Advanced_Appearance {
            get {
                return ResourceManager.GetString("Settings_Advanced_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string Settings_Advanced_Dimensions {
            get {
                return ResourceManager.GetString("Settings_Advanced_Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font family used in widgets.
        /// </summary>
        public static string Settings_Advanced_FontFamily_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Advanced_FontFamily_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Family.
        /// </summary>
        public static string Settings_Advanced_FontFamily_Title {
            get {
                return ResourceManager.GetString("Settings_Advanced_FontFamily_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent accidental widget repositioning.
        /// </summary>
        public static string Settings_Advanced_LockPosition_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Advanced_LockPosition_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock position.
        /// </summary>
        public static string Settings_Advanced_LockPosition_Title {
            get {
                return ResourceManager.GetString("Settings_Advanced_LockPosition_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevent accidental widget resizing.
        /// </summary>
        public static string Settings_Advanced_LockSize_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Advanced_LockSize_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock size.
        /// </summary>
        public static string Settings_Advanced_LockSize_Title {
            get {
                return ResourceManager.GetString("Settings_Advanced_LockSize_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Settings_Advanced_Position {
            get {
                return ResourceManager.GetString("Settings_Advanced_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Settings_Advanced_Size {
            get {
                return ResourceManager.GetString("Settings_Advanced_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align widget position to grid.
        /// </summary>
        public static string Settings_Advanced_SnapPosition_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Advanced_SnapPosition_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap position.
        /// </summary>
        public static string Settings_Advanced_SnapPosition_Title {
            get {
                return ResourceManager.GetString("Settings_Advanced_SnapPosition_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align widget size to grid.
        /// </summary>
        public static string Settings_Advanced_SnapSize_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Advanced_SnapSize_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap size.
        /// </summary>
        public static string Settings_Advanced_SnapSize_Title {
            get {
                return ResourceManager.GetString("Settings_Advanced_SnapSize_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use native window frame.
        /// </summary>
        public static string Settings_Advanced_UseNativeFrame_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Advanced_UseNativeFrame_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native frame.
        /// </summary>
        public static string Settings_Advanced_UseNativeFrame_Title {
            get {
                return ResourceManager.GetString("Settings_Advanced_UseNativeFrame_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal distance between widgets.
        /// </summary>
        public static string Settings_Advanced_WidgetMargin_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Advanced_WidgetMargin_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget margin.
        /// </summary>
        public static string Settings_Advanced_WidgetMargin_Title {
            get {
                return ResourceManager.GetString("Settings_Advanced_WidgetMargin_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius of widget corners.
        /// </summary>
        public static string Settings_Advanced_WidgetRadius_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Advanced_WidgetRadius_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget radius.
        /// </summary>
        public static string Settings_Advanced_WidgetRadius_Title {
            get {
                return ResourceManager.GetString("Settings_Advanced_WidgetRadius_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of the small widget.
        /// </summary>
        public static string Settings_Advanced_WidgetSize_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Advanced_WidgetSize_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget size.
        /// </summary>
        public static string Settings_Advanced_WidgetSize_Title {
            get {
                return ResourceManager.GetString("Settings_Advanced_WidgetSize_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Settings_Appearance {
            get {
                return ResourceManager.GetString("Settings_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Settings_Appearance_AccentColor_Manual {
            get {
                return ResourceManager.GetString("Settings_Appearance_AccentColor_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Settings_Appearance_AccentColor_Null {
            get {
                return ResourceManager.GetString("Settings_Appearance_AccentColor_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent color.
        /// </summary>
        public static string Settings_Appearance_AccentColor_Title {
            get {
                return ResourceManager.GetString("Settings_Appearance_AccentColor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply a theme.
        /// </summary>
        public static string Settings_Appearance_ApplyTheme {
            get {
                return ResourceManager.GetString("Settings_Appearance_ApplyTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string Settings_Appearance_Colors {
            get {
                return ResourceManager.GetString("Settings_Appearance_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Settings_Appearance_DarkMode_False {
            get {
                return ResourceManager.GetString("Settings_Appearance_DarkMode_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Settings_Appearance_DarkMode_Null {
            get {
                return ResourceManager.GetString("Settings_Appearance_DarkMode_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the colors that appear in widget.
        /// </summary>
        public static string Settings_Appearance_DarkMode_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Appearance_DarkMode_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your mode.
        /// </summary>
        public static string Settings_Appearance_DarkMode_Title {
            get {
                return ResourceManager.GetString("Settings_Appearance_DarkMode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark .
        /// </summary>
        public static string Settings_Appearance_DarkMode_True {
            get {
                return ResourceManager.GetString("Settings_Appearance_DarkMode_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets elements appear in the same color.
        /// </summary>
        public static string Settings_Appearance_Monochrome_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Appearance_Monochrome_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monochrome theme.
        /// </summary>
        public static string Settings_Appearance_Monochrome_Title {
            get {
                return ResourceManager.GetString("Settings_Appearance_Monochrome_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity level of widget&apos;s background.
        /// </summary>
        public static string Settings_Appearance_OpacityLevel_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Appearance_OpacityLevel_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity Level.
        /// </summary>
        public static string Settings_Appearance_OpacityLevel_Title {
            get {
                return ResourceManager.GetString("Settings_Appearance_OpacityLevel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inter, round corners, no border, no shadow.
        /// </summary>
        public static string Settings_Appearance_Presets_Apple_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Appearance_Presets_Apple_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple.
        /// </summary>
        public static string Settings_Appearance_Presets_Apple_Title {
            get {
                return ResourceManager.GetString("Settings_Appearance_Presets_Apple_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Settings_Appearance_Presets_Apply {
            get {
                return ResourceManager.GetString("Settings_Appearance_Presets_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segoe UI, sharp corners, native frame.
        /// </summary>
        public static string Settings_Appearance_Presets_Windows_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Appearance_Presets_Windows_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string Settings_Appearance_Presets_Windows_Title {
            get {
                return ResourceManager.GetString("Settings_Appearance_Presets_Windows_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets appear translucent.
        /// </summary>
        public static string Settings_Appearance_Transparency_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Appearance_Transparency_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency effects.
        /// </summary>
        public static string Settings_Appearance_Transparency_Title {
            get {
                return ResourceManager.GetString("Settings_Appearance_Transparency_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Settings_General_Actions {
            get {
                return ResourceManager.GetString("Settings_General_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Settings_General_Exit_Action {
            get {
                return ResourceManager.GetString("Settings_General_Exit_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit the application.
        /// </summary>
        public static string Settings_General_Exit_Title {
            get {
                return ResourceManager.GetString("Settings_General_Exit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_General_Language {
            get {
                return ResourceManager.GetString("Settings_General_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uWidgets will appear in this language.
        /// </summary>
        public static string Settings_General_Language_Subtitle {
            get {
                return ResourceManager.GetString("Settings_General_Language_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display language.
        /// </summary>
        public static string Settings_General_Language_Title {
            get {
                return ResourceManager.GetString("Settings_General_Language_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Settings_General_Restart_Action {
            get {
                return ResourceManager.GetString("Settings_General_Restart_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the application.
        /// </summary>
        public static string Settings_General_Restart_Title {
            get {
                return ResourceManager.GetString("Settings_General_Restart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup.
        /// </summary>
        public static string Settings_General_Startup {
            get {
                return ResourceManager.GetString("Settings_General_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app will start automatically when you start your device.
        /// </summary>
        public static string Settings_General_Startup_Subtitle {
            get {
                return ResourceManager.GetString("Settings_General_Startup_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run on startup.
        /// </summary>
        public static string Settings_General_Startup_Title {
            get {
                return ResourceManager.GetString("Settings_General_Startup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart the app to apply changes.
        /// </summary>
        public static string Settings_RestartRequired {
            get {
                return ResourceManager.GetString("Settings_RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Update_Download {
            get {
                return ResourceManager.GetString("Update_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string Update_Later {
            get {
                return ResourceManager.GetString("Update_Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip This Version.
        /// </summary>
        public static string Update_SkipThisVersion {
            get {
                return ResourceManager.GetString("Update_SkipThisVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Update.
        /// </summary>
        public static string Update_SoftwareUpdate {
            get {
                return ResourceManager.GetString("Update_SoftwareUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uWidgets {0} is available to download.
        /// </summary>
        public static string Update_UpdateFormat {
            get {
                return ResourceManager.GetString("Update_UpdateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widget.
        /// </summary>
        public static string Widget {
            get {
                return ResourceManager.GetString("Widget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Widget_Edit {
            get {
                return ResourceManager.GetString("Widget_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit widgets.
        /// </summary>
        public static string Widget_OpenSettings {
            get {
                return ResourceManager.GetString("Widget_OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove widget.
        /// </summary>
        public static string Widget_Remove {
            get {
                return ResourceManager.GetString("Widget_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Widget_Save {
            get {
                return ResourceManager.GetString("Widget_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Widget_Size {
            get {
                return ResourceManager.GetString("Widget_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Large.
        /// </summary>
        public static string Widget_Size_ExtraLarge {
            get {
                return ResourceManager.GetString("Widget_Size_ExtraLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string Widget_Size_Large {
            get {
                return ResourceManager.GetString("Widget_Size_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Widget_Size_Medium {
            get {
                return ResourceManager.GetString("Widget_Size_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string Widget_Size_Small {
            get {
                return ResourceManager.GetString("Widget_Size_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets.
        /// </summary>
        public static string Widgets {
            get {
                return ResourceManager.GetString("Widgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        public static string Settings_Advanced_GridMode {
            get {
                return ResourceManager.GetString("Settings_Advanced_GridMode", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Grid mode.
        /// </summary>
        public static string Settings_Advanced_GridMode_Title {
            get {
                return ResourceManager.GetString("Settings_Advanced_GridMode_Title", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to How widgets are arranged on the desktop.
        /// </summary>
        public static string Settings_Advanced_GridMode_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Advanced_GridMode_Subtitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Virtual grid.
        /// </summary>
        public static string Settings_Advanced_GridMode_Virtual {
            get {
                return ResourceManager.GetString("Settings_Advanced_GridMode_Virtual", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Manual grid.
        /// </summary>
        public static string Settings_Advanced_GridMode_Manual {
            get {
                return ResourceManager.GetString("Settings_Advanced_GridMode_Manual", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Free layout.
        /// </summary>
        public static string Settings_Advanced_GridMode_Free {
            get {
                return ResourceManager.GetString("Settings_Advanced_GridMode_Free", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        public static string Settings_Advanced_GridColumns_Title {
            get {
                return ResourceManager.GetString("Settings_Advanced_GridColumns_Title", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Number of grid columns (n).
        /// </summary>
        public static string Settings_Advanced_GridColumns_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Advanced_GridColumns_Subtitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        public static string Settings_Advanced_GridRows_Title {
            get {
                return ResourceManager.GetString("Settings_Advanced_GridRows_Title", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Number of grid rows (m).
        /// </summary>
        public static string Settings_Advanced_GridRows_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Advanced_GridRows_Subtitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Cell size.
        /// </summary>
        public static string Settings_Advanced_GridCellSize_Title {
            get {
                return ResourceManager.GetString("Settings_Advanced_GridCellSize_Title", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Cell size, % of the screen width (vertical follows, so cells stay square).
        /// </summary>
        public static string Settings_Advanced_GridCellSize_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Advanced_GridCellSize_Subtitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Grid position.
        /// </summary>
        public static string Settings_Advanced_GridPosition_Title {
            get {
                return ResourceManager.GetString("Settings_Advanced_GridPosition_Title", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Grid area X/Y, % of the working area.
        /// </summary>
        public static string Settings_Advanced_GridPosition_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Advanced_GridPosition_Subtitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Edit grid.
        /// </summary>
        public static string Settings_Advanced_GridEdit {
            get {
                return ResourceManager.GetString("Settings_Advanced_GridEdit", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Drag the grid on the desktop to move it, drag the corner handle to resize cells.
        /// </summary>
        public static string Settings_Advanced_GridEdit_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Advanced_GridEdit_Subtitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Drag to move · drag corner to resize cells · Esc to close.
        /// </summary>
        public static string Settings_Advanced_GridEditorHint {
            get {
                return ResourceManager.GetString("Settings_Advanced_GridEditorHint", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to {0} × {1} · cell {2} px.
        /// </summary>
        public static string Settings_Advanced_GridEditorInfo {
            get {
                return ResourceManager.GetString("Settings_Advanced_GridEditorInfo", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Content scale.
        /// </summary>
        public static string Settings_Advanced_ContentScale_Title {
            get {
                return ResourceManager.GetString("Settings_Advanced_ContentScale_Title", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Scale the widget content (0.5× – 2×).
        /// </summary>
        public static string Settings_Advanced_ContentScale_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Advanced_ContentScale_Subtitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Network.
        /// </summary>
        public static string Settings_Advanced_Network {
            get {
                return ResourceManager.GetString("Settings_Advanced_Network", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to HTTP proxy.
        /// </summary>
        public static string Settings_Advanced_Proxy_Title {
            get {
                return ResourceManager.GetString("Settings_Advanced_Proxy_Title", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to How weather and update requests reach the network. Direct bypasses a stale system proxy.
        /// </summary>
        public static string Settings_Advanced_Proxy_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Advanced_Proxy_Subtitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Direct connection.
        /// </summary>
        public static string Settings_Advanced_Proxy_Direct {
            get {
                return ResourceManager.GetString("Settings_Advanced_Proxy_Direct", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to System proxy.
        /// </summary>
        public static string Settings_Advanced_Proxy_System {
            get {
                return ResourceManager.GetString("Settings_Advanced_Proxy_System", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Custom....
        /// </summary>
        public static string Settings_Advanced_Proxy_Custom {
            get {
                return ResourceManager.GetString("Settings_Advanced_Proxy_Custom", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Custom proxy URL.
        /// </summary>
        public static string Settings_Advanced_ProxyCustom_Title {
            get {
                return ResourceManager.GetString("Settings_Advanced_ProxyCustom_Title", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Used when the proxy mode is Custom.
        /// </summary>
        public static string Settings_Advanced_ProxyCustom_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Advanced_ProxyCustom_Subtitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to http://host:port.
        /// </summary>
        public static string Settings_Advanced_ProxyCustom_Watermark {
            get {
                return ResourceManager.GetString("Settings_Advanced_ProxyCustom_Watermark", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Update source.
        /// </summary>
        public static string Settings_Advanced_UpdateUrl_Title {
            get {
                return ResourceManager.GetString("Settings_Advanced_UpdateUrl_Title", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Custom update URL (releases/latest page); empty disables update checks.
        /// </summary>
        public static string Settings_Advanced_UpdateUrl_Subtitle {
            get {
                return ResourceManager.GetString("Settings_Advanced_UpdateUrl_Subtitle", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to 1×1.
        /// </summary>
        public static string Widget_Size_Single {
            get {
                return ResourceManager.GetString("Widget_Size_Single", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Grid size.
        /// </summary>
        public static string Widget_Size_Grid {
            get {
                return ResourceManager.GetString("Widget_Size_Grid", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Search fonts....
        /// </summary>
        public static string Settings_Appearance_FontSearchWatermark {
            get {
                return ResourceManager.GetString("Settings_Appearance_FontSearchWatermark", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to No matching fonts.
        /// </summary>
        public static string Settings_Appearance_FontNoResults {
            get {
                return ResourceManager.GetString("Settings_Appearance_FontNoResults", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; close.
        /// </summary>
        public static string Settings_Advanced_GridEditorSave {
            get {
                return ResourceManager.GetString("Settings_Advanced_GridEditorSave", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to Center on X axis.
        /// </summary>
        public static string Settings_Advanced_GridEditorCenterX {
            get {
                return ResourceManager.GetString("Settings_Advanced_GridEditorCenterX", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to ←.
        /// </summary>
        public static string Settings_Advanced_GridEditorNudgeLeft {
            get {
                return ResourceManager.GetString("Settings_Advanced_GridEditorNudgeLeft", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to →.
        /// </summary>
        public static string Settings_Advanced_GridEditorNudgeRight {
            get {
                return ResourceManager.GetString("Settings_Advanced_GridEditorNudgeRight", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to ↑.
        /// </summary>
        public static string Settings_Advanced_GridEditorNudgeUp {
            get {
                return ResourceManager.GetString("Settings_Advanced_GridEditorNudgeUp", resourceCulture);
            }
        }        
        /// <summary>
        ///   Looks up a localized string similar to ↓.
        /// </summary>
        public static string Settings_Advanced_GridEditorNudgeDown {
            get {
                return ResourceManager.GetString("Settings_Advanced_GridEditorNudgeDown", resourceCulture);
            }
        }    }
}
