//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Folders.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Folders.Locales.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        public static string Folders_Title {
            get {
                return ResourceManager.GetString("Folders_Title", resourceCulture);
            }
        }
        
        public static string Folders_Subtitle {
            get {
                return ResourceManager.GetString("Folders_Subtitle", resourceCulture);
            }
        }
        
        public static string Folders_Empty {
            get {
                return ResourceManager.GetString("Folders_Empty", resourceCulture);
            }
        }
        
        public static string Folders_Open {
            get {
                return ResourceManager.GetString("Folders_Open", resourceCulture);
            }
        }
        
        public static string Folders_Remove {
            get {
                return ResourceManager.GetString("Folders_Remove", resourceCulture);
            }
        }
        
        public static string Folders_Add {
            get {
                return ResourceManager.GetString("Folders_Add", resourceCulture);
            }
        }
        
        public static string Folders_Add_Hint {
            get {
                return ResourceManager.GetString("Folders_Add_Hint", resourceCulture);
            }
        }
        
        public static string Folders_Browse {
            get {
                return ResourceManager.GetString("Folders_Browse", resourceCulture);
            }
        }
        
        public static string Folders_Clear {
            get {
                return ResourceManager.GetString("Folders_Clear", resourceCulture);
            }
        }
        
        public static string Folders_Help {
            get {
                return ResourceManager.GetString("Folders_Help", resourceCulture);
            }
        }
    public static string Folders_ShowNames {
            get {
                return ResourceManager.GetString("Folders_ShowNames", resourceCulture);
            }
        }
        
        public static string Folders_Columns {
            get {
                return ResourceManager.GetString("Folders_Columns", resourceCulture);
            }
        }
        
        public static string Folders_RowSpacing {
            get {
                return ResourceManager.GetString("Folders_RowSpacing", resourceCulture);
            }
        }
        
        public static string Folders_ShowScrollbar {
            get {
                return ResourceManager.GetString("Folders_ShowScrollbar", resourceCulture);
            }
        }
        
        public static string Folders_ShowTitle {
            get {
                return ResourceManager.GetString("Folders_ShowTitle", resourceCulture);
            }
        }
        
        public static string Folders_ClassicIcon {
            get {
                return ResourceManager.GetString("Folders_ClassicIcon", resourceCulture);
            }
        }
        
        public static string Folders_PickFolder {
            get {
                return ResourceManager.GetString("Folders_PickFolder", resourceCulture);
            }
        }
        
        public static string Folders_PickFile {
            get {
                return ResourceManager.GetString("Folders_PickFile", resourceCulture);
            }
        }

        public static string Folders_IconSize {
            get {
                return ResourceManager.GetString("Folders_IconSize", resourceCulture);
            }
        }

        public static string Folders_FontSize {
            get {
                return ResourceManager.GetString("Folders_FontSize", resourceCulture);
            }
        }

        public static string Folders_Layout {
            get {
                return ResourceManager.GetString("Folders_Layout", resourceCulture);
            }
        }

        public static string Folders_Layout_Grid {
            get {
                return ResourceManager.GetString("Folders_Layout_Grid", resourceCulture);
            }
        }

        public static string Folders_Layout_List {
            get {
                return ResourceManager.GetString("Folders_Layout_List", resourceCulture);
            }
        }

        public static string Folders_TitleLabel {
            get {
                return ResourceManager.GetString("Folders_TitleLabel", resourceCulture);
            }
        }

        public static string Folders_TitleOffset {
            get {
                return ResourceManager.GetString("Folders_TitleOffset", resourceCulture);
            }
        }

        public static string Folders_BoldTitle {
            get {
                return ResourceManager.GetString("Folders_BoldTitle", resourceCulture);
            }
        }

        public static string Folders_BoldNames {
            get {
                return ResourceManager.GetString("Folders_BoldNames", resourceCulture);
            }
        }

        public static string Folders_WatchFolder {
            get {
                return ResourceManager.GetString("Folders_WatchFolder", resourceCulture);
            }
        }

        public static string Folders_WatchPick {
            get {
                return ResourceManager.GetString("Folders_WatchPick", resourceCulture);
            }
        }

        public static string Folders_WatchClear {
            get {
                return ResourceManager.GetString("Folders_WatchClear", resourceCulture);
            }
        }

        public static string Folders_WatchHint {
            get {
                return ResourceManager.GetString("Folders_WatchHint", resourceCulture);
            }
        }

        public static string Folders_Empty_Folder {
            get {
                return ResourceManager.GetString("Folders_Empty_Folder", resourceCulture);
            }
        }

        public static string Folders_Group_Content {
            get {
                return ResourceManager.GetString("Folders_Group_Content", resourceCulture);
            }
        }

        public static string Folders_Group_Name {
            get {
                return ResourceManager.GetString("Folders_Group_Name", resourceCulture);
            }
        }

        public static string Folders_Group_Title {
            get {
                return ResourceManager.GetString("Folders_Group_Title", resourceCulture);
            }
        }

        public static string Folders_Group_Appearance {
            get {
                return ResourceManager.GetString("Folders_Group_Appearance", resourceCulture);
            }
        }

        public static string Folders_Group_Items {
            get {
                return ResourceManager.GetString("Folders_Group_Items", resourceCulture);
            }
        }

        public static string Folders_MaxNameLines {
            get {
                return ResourceManager.GetString("Folders_MaxNameLines", resourceCulture);
            }
        }

        public static string Folders_MaxNameChars {
            get {
                return ResourceManager.GetString("Folders_MaxNameChars", resourceCulture);
            }
        }

        public static string Folders_CamelCaseWrap {
            get {
                return ResourceManager.GetString("Folders_CamelCaseWrap", resourceCulture);
            }
        }

        public static string Folders_WatchSort {
            get {
                return ResourceManager.GetString("Folders_WatchSort", resourceCulture);
            }
        }

        public static string Folders_WatchDirsFirst {
            get {
                return ResourceManager.GetString("Folders_WatchDirsFirst", resourceCulture);
            }
        }

        public static string Folders_WatchShowHidden {
            get {
                return ResourceManager.GetString("Folders_WatchShowHidden", resourceCulture);
            }
        }

        public static string Folders_SortName {
            get {
                return ResourceManager.GetString("Folders_SortName", resourceCulture);
            }
        }

        public static string Folders_SortCreated {
            get {
                return ResourceManager.GetString("Folders_SortCreated", resourceCulture);
            }
        }

        public static string Folders_SortModified {
            get {
                return ResourceManager.GetString("Folders_SortModified", resourceCulture);
            }
        }

        public static string Folders_Padding {
            get {
                return ResourceManager.GetString("Folders_Padding", resourceCulture);
            }
        }

        public static string Folders_WatchHideExt {
            get {
                return ResourceManager.GetString("Folders_WatchHideExt", resourceCulture);
            }
        }

        public static string Folders_WatchDesc {
            get {
                return ResourceManager.GetString("Folders_WatchDesc", resourceCulture);
            }
        }

        public static string Folders_WatchHideSubfolders {
            get {
                return ResourceManager.GetString("Folders_WatchHideSubfolders", resourceCulture);
            }
        }

        public static string Folders_RowLayout {
            get {
                return ResourceManager.GetString("Folders_RowLayout", resourceCulture);
            }
        }

        public static string Folders_RowLayout_Auto {
            get {
                return ResourceManager.GetString("Folders_RowLayout_Auto", resourceCulture);
            }
        }

        public static string Folders_RowLayout_Fixed {
            get {
                return ResourceManager.GetString("Folders_RowLayout_Fixed", resourceCulture);
            }
        }

        public static string Folders_SingleFile_Title {
            get {
                return ResourceManager.GetString("Folders_SingleFile_Title", resourceCulture);
            }
        }

        public static string Folders_SingleFile_Subtitle {
            get {
                return ResourceManager.GetString("Folders_SingleFile_Subtitle", resourceCulture);
            }
        }

        public static string Folders_SingleFile_IconPercent {
            get {
                return ResourceManager.GetString("Folders_SingleFile_IconPercent", resourceCulture);
            }
        }

        public static string Folders_SingleFile_Target {
            get {
                return ResourceManager.GetString("Folders_SingleFile_Target", resourceCulture);
            }
        }

        public static string Folders_SingleFile_Pick {
            get {
                return ResourceManager.GetString("Folders_SingleFile_Pick", resourceCulture);
            }
        }

        public static string Folders_SingleFile_EmptyHint {
            get {
                return ResourceManager.GetString("Folders_SingleFile_EmptyHint", resourceCulture);
            }
        }

        public static string Folders_BigFolder_Title {
            get {
                return ResourceManager.GetString("Folders_BigFolder_Title", resourceCulture);
            }
        }

        public static string Folders_BigFolder_Subtitle {
            get {
                return ResourceManager.GetString("Folders_BigFolder_Subtitle", resourceCulture);
            }
        }

        public static string Folders_BigFolder_Density {
            get {
                return ResourceManager.GetString("Folders_BigFolder_Density", resourceCulture);
            }
        }

        public static string Folders_BigFolder_Sparse {
            get {
                return ResourceManager.GetString("Folders_BigFolder_Sparse", resourceCulture);
            }
        }

        public static string Folders_BigFolder_Dense {
            get {
                return ResourceManager.GetString("Folders_BigFolder_Dense", resourceCulture);
            }
        }

        public static string Folders_BigFolder_EmptyHint {
            get {
                return ResourceManager.GetString("Folders_BigFolder_EmptyHint", resourceCulture);
            }
        }

        public static string Folders_BigFolder_Spacing {
            get {
                return ResourceManager.GetString("Folders_BigFolder_Spacing", resourceCulture);
            }
        }

        public static string Folders_BigFolder_Custom {
            get {
                return ResourceManager.GetString("Folders_BigFolder_Custom", resourceCulture);
            }
        }

        public static string Folders_BigFolder_CustomColumns {
            get {
                return ResourceManager.GetString("Folders_BigFolder_CustomColumns", resourceCulture);
            }
        }

        public static string Folders_BigFolder_CustomRows {
            get {
                return ResourceManager.GetString("Folders_BigFolder_CustomRows", resourceCulture);
            }
        }

        public static string Folders_BigFolder_ViewAll {
            get {
                return ResourceManager.GetString("Folders_BigFolder_ViewAll", resourceCulture);
            }
        }

        public static string Folders_BigFolder_AllFiles {
            get {
                return ResourceManager.GetString("Folders_BigFolder_AllFiles", resourceCulture);
            }
        }

        public static string Folders_BigFolder_PopupGroup {
            get {
                return ResourceManager.GetString("Folders_BigFolder_PopupGroup", resourceCulture);
            }
        }

        public static string Folders_BigFolder_FolderName {
            get {
                return ResourceManager.GetString("Folders_BigFolder_FolderName", resourceCulture);
            }
        }

        public static string Folders_BigFolder_FolderName_Hint {
            get {
                return ResourceManager.GetString("Folders_BigFolder_FolderName_Hint", resourceCulture);
            }
        }

        public static string Folders_BigFolder_PopupIconSize {
            get {
                return ResourceManager.GetString("Folders_BigFolder_PopupIconSize", resourceCulture);
            }
        }

        public static string Folders_BigFolder_PopupSpacing {
            get {
                return ResourceManager.GetString("Folders_BigFolder_PopupSpacing", resourceCulture);
            }
        }

        public static string Folders_BigFolder_PopupPadding {
            get {
                return ResourceManager.GetString("Folders_BigFolder_PopupPadding", resourceCulture);
            }
        }

        public static string Folders_BigFolder_PopupColumns {
            get {
                return ResourceManager.GetString("Folders_BigFolder_PopupColumns", resourceCulture);
            }
        }

        public static string Folders_BigFolder_PopupShowNames {
            get {
                return ResourceManager.GetString("Folders_BigFolder_PopupShowNames", resourceCulture);
            }
        }

        public static string Folders_BigFolder_PopupShowExtensions {
            get {
                return ResourceManager.GetString("Folders_BigFolder_PopupShowExtensions", resourceCulture);
            }
        }
    }
}
