//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notes.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Notes.Locales.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get quick access to one of your notes.
        /// </summary>
        public static string Notes_Subtitle {
            get {
                return ResourceManager.GetString("Notes_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Notes_Title {
            get {
                return ResourceManager.GetString("Notes_Title", resourceCulture);
            }
        }
        
        public static string Notes_Markdown {
            get {
                return ResourceManager.GetString("Notes_Markdown", resourceCulture);
            }
        }
        
        public static string Notes_Header_Color {
            get {
                return ResourceManager.GetString("Notes_Header_Color", resourceCulture);
            }
        }
        
        public static string Notes_Header_FollowAccent {
            get {
                return ResourceManager.GetString("Notes_Header_FollowAccent", resourceCulture);
            }
        }
        
        public static string Notes_Header_Custom {
            get {
                return ResourceManager.GetString("Notes_Header_Custom", resourceCulture);
            }
        }
        
        public static string Notes_Header_Opacity {
            get {
                return ResourceManager.GetString("Notes_Header_Opacity", resourceCulture);
            }
        }
        
        public static string Notes_Source {
            get {
                return ResourceManager.GetString("Notes_Source", resourceCulture);
            }
        }
        
        public static string Notes_Source_Internal {
            get {
                return ResourceManager.GetString("Notes_Source_Internal", resourceCulture);
            }
        }
        
        public static string Notes_Source_File {
            get {
                return ResourceManager.GetString("Notes_Source_File", resourceCulture);
            }
        }
        
        public static string Notes_Source_Folder {
            get {
                return ResourceManager.GetString("Notes_Source_Folder", resourceCulture);
            }
        }
        
        public static string Notes_Browse {
            get {
                return ResourceManager.GetString("Notes_Browse", resourceCulture);
            }
        }
        
        public static string Notes_Documents_Count {
            get {
                return ResourceManager.GetString("Notes_Documents_Count", resourceCulture);
            }
        }
        
        public static string Notes_Documents_Order {
            get {
                return ResourceManager.GetString("Notes_Documents_Order", resourceCulture);
            }
        }
        
        public static string Notes_Order_Recent {
            get {
                return ResourceManager.GetString("Notes_Order_Recent", resourceCulture);
            }
        }
        
        public static string Notes_Order_Manual {
            get {
                return ResourceManager.GetString("Notes_Order_Manual", resourceCulture);
            }
        }
        
        public static string Notes_Selected_Files {
            get {
                return ResourceManager.GetString("Notes_Selected_Files", resourceCulture);
            }
        }
        
        public static string Notes_Empty {
            get {
                return ResourceManager.GetString("Notes_Empty", resourceCulture);
            }
        }
        
        public static string Notes_Body_Padding {
            get {
                return ResourceManager.GetString("Notes_Body_Padding", resourceCulture);
            }
        }
        
        public static string Notes_Markdown_Style {
            get {
                return ResourceManager.GetString("Notes_Markdown_Style", resourceCulture);
            }
        }
        
        public static string Notes_Markdown_Style_Subtitle {
            get {
                return ResourceManager.GetString("Notes_Markdown_Style_Subtitle", resourceCulture);
            }
        }
        
        public static string Notes_Style_Font {
            get {
                return ResourceManager.GetString("Notes_Style_Font", resourceCulture);
            }
        }
        
        public static string Notes_Style_Font_Default {
            get {
                return ResourceManager.GetString("Notes_Style_Font_Default", resourceCulture);
            }
        }
        
        public static string Notes_Style_Mode {
            get {
                return ResourceManager.GetString("Notes_Style_Mode", resourceCulture);
            }
        }
        
        public static string Notes_Style_Mode_Light {
            get {
                return ResourceManager.GetString("Notes_Style_Mode_Light", resourceCulture);
            }
        }
        
        public static string Notes_Style_Mode_Dark {
            get {
                return ResourceManager.GetString("Notes_Style_Mode_Dark", resourceCulture);
            }
        }
        
        public static string Notes_Style_Text {
            get {
                return ResourceManager.GetString("Notes_Style_Text", resourceCulture);
            }
        }
        
        public static string Notes_Style_Heading {
            get {
                return ResourceManager.GetString("Notes_Style_Heading", resourceCulture);
            }
        }
        
        public static string Notes_Style_Bold {
            get {
                return ResourceManager.GetString("Notes_Style_Bold", resourceCulture);
            }
        }
        
        public static string Notes_Style_Italic {
            get {
                return ResourceManager.GetString("Notes_Style_Italic", resourceCulture);
            }
        }
        
        public static string Notes_Style_Strike {
            get {
                return ResourceManager.GetString("Notes_Style_Strike", resourceCulture);
            }
        }
        
        public static string Notes_Style_Link {
            get {
                return ResourceManager.GetString("Notes_Style_Link", resourceCulture);
            }
        }
        
        public static string Notes_Style_Link_Subtitle {
            get {
                return ResourceManager.GetString("Notes_Style_Link_Subtitle", resourceCulture);
            }
        }
        
        public static string Notes_Style_Code {
            get {
                return ResourceManager.GetString("Notes_Style_Code", resourceCulture);
            }
        }
        
        public static string Notes_Style_Code_Subtitle {
            get {
                return ResourceManager.GetString("Notes_Style_Code_Subtitle", resourceCulture);
            }
        }
        
        public static string Notes_Style_Quote {
            get {
                return ResourceManager.GetString("Notes_Style_Quote", resourceCulture);
            }
        }
        
        public static string Notes_Style_Reset {
            get {
                return ResourceManager.GetString("Notes_Style_Reset", resourceCulture);
            }
        }
        
        public static string Notes_Style_Preset {
            get {
                return ResourceManager.GetString("Notes_Style_Preset", resourceCulture);
            }
        }
        
        public static string Notes_Preset_Import {
            get {
                return ResourceManager.GetString("Notes_Preset_Import", resourceCulture);
            }
        }
        
        public static string Notes_Preset_Export {
            get {
                return ResourceManager.GetString("Notes_Preset_Export", resourceCulture);
            }
        }
        
        public static string Notes_Preset_Filter {
            get {
                return ResourceManager.GetString("Notes_Preset_Filter", resourceCulture);
            }
        }
        
        public static string Notes_Preset_Imported {
            get {
                return ResourceManager.GetString("Notes_Preset_Imported", resourceCulture);
            }
        }
        
        public static string Notes_Preset_Exported {
            get {
                return ResourceManager.GetString("Notes_Preset_Exported", resourceCulture);
            }
        }
        
        public static string Notes_Preset_Failed {
            get {
                return ResourceManager.GetString("Notes_Preset_Failed", resourceCulture);
            }
        }
    }
}
